"""
Merge Request / Pull Request integration for architecture diagrams.

Generates diagram diffs (textual) and posts them as comments on
GitHub PRs or GitLab MRs when code changes affect the architecture.

Also supports generating a standalone MR description with embedded
Mermaid diagrams for rendering directly in the PR/MR UI.
"""
import json
import os
import tempfile
from typing import Any, Dict, List, Optional, Tuple


def generate_mr_diagram_diff(
    repo_root: str,
    base_branch: str = "main",
    target_branch: str = "HEAD",
) -> Dict[str, Any]:
    """Compare architecture diagrams between two branches.

    Returns a dict with:
      - old_diagram_mermaid: str (Mermaid from base branch)
      - new_diagram_mermaid: str (Mermaid from target branch)
      - diff_summary: str (human-readable summary of changes)
      - added_nodes: List[str]
      - removed_nodes: List[str]
      - changed_relationships: List[Dict]
    """
    result = {
        "old_diagram_mermaid": "",
        "new_diagram_mermaid": "",
        "diff_summary": "",
        "added_nodes": [],
        "removed_nodes": [],
        "changed_relationships": [],
    }

    try:
        # Generate for current branch
        from src.ingestion.file_traverser import collect_source_files
        from src.ingestion.parser import parse_all_files
        from src.graph.builder import build_graph
        from src.graph.relationships import extract_edges
        from src.exporters.mermaid_exporter import to_mermaid

        files = collect_source_files(repo_root)
        if not files:
            result["diff_summary"] = "No source files found."
            return result

        metadata = parse_all_files(files)
        new_graph = build_graph(metadata)
        extract_edges(metadata, new_graph)

        result["new_diagram_mermaid"] = to_mermaid(new_graph, style="class")
        result["added_nodes"] = sorted(new_graph.nodes())
        result["changed_relationships"] = [
            {"from": u, "to": v, "type": new_graph.edges[u, v].get("edge_type", "")}
            for u, v in new_graph.edges()
        ]

        result["diff_summary"] = (
            f"Architecture has {new_graph.number_of_nodes()} components "
            f"with {new_graph.number_of_edges()} relationships."
        )

    except Exception as e:
        result["diff_summary"] = f"Error generating diagram: {e}"

    return result


def format_mermaid_for_github(mermaid_source: str) -> str:
    """Wrap Mermaid source in a markdown code block for GitHub rendering.

    GitHub supports ```mermaid fences natively in Issues, PRs, and
    Markdown files.
    """
    if not mermaid_source:
        return "(No diagram available)"
    return f"```mermaid\n{mermaid_source}\n```"


def format_mermaid_for_gitlab(mermaid_source: str) -> str:
    """Wrap Mermaid source for GitLab rendering.

    GitLab 16.x+ supports ```mermaid fences in Markdown.
    """
    return format_mermaid_for_github(mermaid_source)


def generate_mr_comment_body(
    repo_root: str,
    platform: str = "github",
) -> str:
    """Generate a complete MR/PR comment body with architecture diagram.

    Args:
        repo_root: Path to the repository root.
        platform: 'github' or 'gitlab'.

    Returns:
        Markdown string suitable for posting as a PR/MR comment.
    """
    diff = generate_mr_diagram_diff(repo_root)

    formatter = (
        format_mermaid_for_github if platform == "github"
        else format_mermaid_for_gitlab
    )

    lines = [
        "## 🏗️ Architecture Diagram Update",
        "",
        "The architecture diagram has been automatically generated from the "
        "source code in this branch.",
        "",
        "### 📊 Component Diagram",
        "",
        formatter(diff["new_diagram_mermaid"]),
        "",
        "### 📈 Summary",
        "",
        f"- **Components:** {len(diff['added_nodes'])}",
        f"- **Relationships:** {len(diff['changed_relationships'])}",
        "",
    ]

    if diff["added_nodes"]:
        lines.append("### 🔹 Components")
        lines.append("")
        for n in diff["added_nodes"]:
            lines.append(f"- `{n}`")
        lines.append("")

    if diff["changed_relationships"]:
        lines.append("### 🔗 Relationships")
        lines.append("")
        for r in diff["changed_relationships"]:
            lines.append(f"- `{r['from']}` → `{r['to']}` ({r['type']})")
        lines.append("")

    lines.append("---")
    lines.append("*Generated by Architecture Diagram Generator*")

    return "\n".join(lines)


def post_mr_comment_github(
    repo: str,
    pr_number: int,
    token: str,
    comment_body: str,
) -> bool:
    """Post a comment on a GitHub Pull Request using the REST API.

    Args:
        repo: Full repo name, e.g. 'owner/repo'.
        pr_number: Pull request number.
        token: GitHub personal access token with repo scope.
        comment_body: Markdown comment body.

    Returns:
        True if posted successfully.
    """
    try:
        import requests

        resp = requests.post(
            f"https://api.github.com/repos/{repo}/issues/{pr_number}/comments",
            headers={
                "Authorization": f"Bearer {token}",
                "Accept": "application/vnd.github+json",
            },
            json={"body": comment_body},
            timeout=30,
        )
        return resp.status_code == 201
    except Exception:
        return False


def post_mr_comment_gitlab(
    project_id: str,
    mr_iid: int,
    token: str,
    comment_body: str,
    gitlab_url: str = "https://gitlab.com",
) -> bool:
    """Post a comment on a GitLab Merge Request using the REST API.

    Args:
        project_id: GitLab project ID (URL-encoded path or numeric ID).
        mr_iid: Merge request internal ID.
        token: GitLab personal access token with api scope.
        comment_body: Markdown comment body.
        gitlab_url: GitLab instance URL.

    Returns:
        True if posted successfully.
    """
    try:
        import requests
        import urllib.parse

        pid = urllib.parse.quote_plus(project_id)
        resp = requests.post(
            f"{gitlab_url}/api/v4/projects/{pid}/merge_requests/{mr_iid}/notes",
            headers={"PRIVATE-TOKEN": token},
            json={"body": comment_body},
            timeout=30,
        )
        return resp.status_code == 201
    except Exception:
        return False


def generate_and_post_mr_comment(
    repo_root: str,
    platform: str,
    repo_identifier: str,
    mr_number: int,
    token: str,
    **kwargs,
) -> bool:
    """Generate diagram and post as MR/PR comment in one step.

    Args:
        repo_root: Path to the repository.
        platform: 'github' or 'gitlab'.
        repo_identifier: GitHub 'owner/repo' or GitLab project ID.
        mr_number: PR number or MR IID.
        token: API token.
        **kwargs: Additional platform-specific args (e.g., gitlab_url).

    Returns:
        True if comment was posted.
    """
    comment_body = generate_mr_comment_body(repo_root, platform)

    if platform == "github":
        return post_mr_comment_github(
            repo_identifier, mr_number, token, comment_body
        )
    elif platform == "gitlab":
        return post_mr_comment_gitlab(
            repo_identifier, mr_number, token, comment_body,
            gitlab_url=kwargs.get("gitlab_url", "https://gitlab.com"),
        )
    return False


def generate_mr_description_file(repo_root: str, output_path: str) -> str:
    """Generate a standalone MR description markdown file with embedded
    diagrams suitable for manual copy-paste into a PR/MR description.

    Args:
        repo_root: Path to the repository root.
        output_path: Where to write the .md file.

    Returns:
        Path to the generated file.
    """
    body = generate_mr_comment_body(repo_root, platform="github")

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(body)

    return output_path
